[package]
name = "advent2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bit_range = "0.1"
regex = "1.5"
criterion = "0.3"

[[bench]]
name = "day21_bench"
harness = false
